const {test, expect} = require('@playwright/test');

test('ADMIN pausa com motivo, consulta histórico e reativa com nova data-base', async ({page}) => {
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('/login');
  await page.getByLabel('E-mail', {exact:true}).fill('admin@browser.example.test');
  await page.getByLabel('Senha', {exact:true}).fill('Browser-test-password-123');
  await page.getByRole('button', {name:'Entrar na minha conta'}).click();
  const code = `PAUSA-${Date.now()}`;
  const today = new Intl.DateTimeFormat('en-CA', {timeZone:'America/Sao_Paulo'}).format(new Date());
  const newStart = new Date(`${today}T12:00:00Z`);
  newStart.setUTCDate(newStart.getUTCDate()+9);
  const iso = newStart.toISOString().slice(0,10);
  const display = iso.split('-').reverse().join('/');
  await page.goto('/checklists/novo');
  await page.getByLabel('Código *', {exact:true}).fill(code);
  await page.getByLabel('Nome *', {exact:true}).fill('Preventiva — pausa e reativação');
  await page.getByLabel('Área / setor *', {exact:true}).fill('Oficina');
  await page.getByLabel('Periodicidade em dias *', {exact:true}).fill('15');
  await page.getByLabel('Data inicial *', {exact:true}).fill(today);
  await page.getByRole('button', {name:'Cadastrar checklist',exact:true}).click();
  await expect(page).toHaveURL(/\/checklists\/\d+$/);
  const detail = new URL(page.url()).pathname;
  await page.getByRole('link', {name:'PAUSAR',exact:true}).click();
  await expect(page.getByLabel('Motivo da pausa *')).toHaveAttribute('required','required');
  await page.getByRole('link', {name:'Cancelar',exact:true}).click();
  await expect(page.getByText('ATIVO', {exact:true})).toBeVisible();
  await page.getByRole('link', {name:'PAUSAR',exact:true}).click();
  await page.getByLabel('Motivo da pausa *').fill('Equipamento fora de operação');
  await page.screenshot({path:'tmp/screenshots/fase4-pausa-desktop.png',fullPage:true});
  await page.getByRole('button', {name:'Confirmar pausa',exact:true}).click();
  await expect(page.getByText('Checklist pausado com sucesso.',{exact:true})).toBeVisible();
  await expect(page.getByText('PAUSADO',{exact:true})).toBeVisible();
  await page.goto(`/?status=PAUSADO&q=${code}`);
  const row = page.locator('#checklist-summary tbody tr');
  await expect(row).toHaveCount(1);
  await expect(row).toContainText('Equipamento fora de operação');
  await expect(row).toContainText('Teste ADMIN');
  await expect(row).toContainText('15 dias');
  await expect(page.locator('[data-occurrence]')).toHaveCount(0);
  await page.screenshot({path:'tmp/screenshots/fase4-pausados-desktop.png',fullPage:true});
  await row.getByRole('link',{name:'REATIVAR',exact:true}).click();
  await expect(page.getByLabel('Nova data inicial *')).toHaveValue('');
  await page.getByLabel('Nova data inicial *').fill(iso);
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('#main-shell')).toHaveCSS('margin-left', '0px');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'tmp/screenshots/fase4-reativacao-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Confirmar reativação',exact:true}).click();
  await expect(page.getByText('Checklist reativado com sucesso.',{exact:true})).toBeVisible();
  await page.goto(`/?q=${code}`);
  await expect(page.locator('#checklist-summary')).toContainText(display);
  await expect(page.locator('#checklist-summary')).toContainText('Faltam 9 dias');
  await expect(page.locator('[data-occurrence]')).toHaveCount(0);
  await page.goto(`/?status=PAUSADO&q=${code}`);
  await expect(page.locator('#checklist-summary')).toContainText('Nenhum checklist nesta seleção');
  await page.goto(`${detail}/historico`);
  await expect(page.getByText(/Checklist pausado por Teste ADMIN/)).toBeVisible();
  await expect(page.getByText(/Checklist reativado por Teste ADMIN/)).toBeVisible();
  await expect(page.locator('[data-history-occurrence]')).toHaveCount(1);
  await expect(page.locator('[data-history-occurrence]')).toContainText('Programação encerrada');
  await expect(page.getByRole('link',{name:'CIENTE',exact:true})).toHaveCount(0);
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('link',{name:'Sair',exact:true}).click();
  await page.getByLabel('E-mail', {exact:true}).fill('usuario@browser.example.test');
  await page.getByLabel('Senha', {exact:true}).fill('Browser-test-password-123');
  await page.getByRole('button', {name:'Entrar na minha conta'}).click();
  await page.goto(detail);
  await expect(page.getByRole('link',{name:'PAUSAR',exact:true})).toHaveCount(0);
  await expect(page.getByRole('link',{name:'REATIVAR',exact:true})).toHaveCount(0);
});
