<?php $this->assign('title', $checklist->name); ?>
<a class="mb-5 inline-block text-sm text-slate-500" href="<?= $this->Url->build('/checklists') ?>">← Voltar para checklists</a>
<div class="mb-7 flex flex-wrap items-start justify-between gap-4">
    <div><p class="mb-2 text-sm font-semibold text-brand-700"><?= h($checklist->code) ?></p><h1 class="page-title break-words"><?= h($checklist->name) ?></h1><p class="muted mt-2"><?= h($checklist->area) ?></p></div>
    <div class="flex flex-wrap gap-3"><a class="btn-secondary" href="<?= $this->Url->build(['controller' => 'History', 'action' => 'checklist', $checklist->id]) ?>">Ver histórico</a><?php if ($isAdmin): ?><a class="btn-secondary" href="<?= $this->Url->build(['controller' => 'Lifecycle', 'action' => $checklist->status === 'ATIVO' ? 'pause' : 'reactivate', $checklist->id]) ?>"><?= $checklist->status === 'ATIVO' ? 'PAUSAR' : 'REATIVAR' ?></a><a class="btn" href="<?= $this->Url->build(['action' => 'edit', $checklist->id]) ?>">Editar checklist</a><?php endif; ?></div>
</div>
<?php if ($checklist->status === 'PAUSADO'): ?><section class="panel mb-6 p-5"><h2 class="font-semibold">Checklist pausado · fora dos alertas</h2><p class="muted mt-2"><?= h($checklist->paused_at?->setTimezone('America/Sao_Paulo')->format('d/m/Y H:i:s') ?? 'Data não registrada') ?></p><p class="mt-2 whitespace-pre-wrap break-words text-sm">Motivo: <?= h($checklist->pause_reason ?? 'Não registrado') ?></p></section><?php endif; ?>
<div class="grid items-start gap-6 lg:grid-cols-[1fr_320px]"><section class="panel p-6"><div class="mb-6 flex items-center justify-between"><h2 class="text-lg font-semibold">Informações gerais</h2><span class="badge <?= $checklist->status === 'PAUSADO' ? 'badge-paused' : '' ?>"><?= h($checklist->status) ?></span></div><dl class="grid gap-6 sm:grid-cols-2"><?php foreach (['Código' => $checklist->code, 'Área / setor' => $checklist->area, 'Rota' => $checklist->route] as $label => $value): ?><div><dt class="muted"><?= h($label) ?></dt><dd class="mt-1 break-words font-medium"><?= h($value ?: 'Não informada') ?></dd></div><?php endforeach; ?></dl>
<?php foreach (['Descrição' => $checklist->description, 'Observação' => $checklist->notes] as $label => $value): ?><div class="mt-6 border-t border-slate-100 pt-5"><h3 class="mb-2 text-sm font-semibold"><?= h($label) ?></h3><p class="whitespace-pre-wrap break-words text-sm leading-relaxed text-slate-600"><?= h($value ?: 'Não informada.') ?></p></div><?php endforeach; ?>
<div class="mt-6 border-t border-slate-100 pt-5 text-xs leading-relaxed text-slate-400">Criado em <?= h($checklist->created->setTimezone('America/Sao_Paulo')->format('d/m/Y H:i')) ?><br>Atualizado em <?= h($checklist->modified->setTimezone('America/Sao_Paulo')->format('d/m/Y H:i')) ?> · horário de Brasília</div></section>
<aside class="panel p-6"><span class="text-brand-600"><?= $this->element('icon', ['name' => 'clock', 'class' => 'size-7']) ?></span><h2 class="mb-5 mt-3 text-lg font-semibold"><?= $checklist->status === 'ATIVO' ? 'Programação ativa' : 'Programação encerrada' ?></h2><p class="muted">Repetir a cada</p><p class="mt-1 text-3xl font-bold"><?= h($schedule?->interval_days ?? '—') ?> <span class="text-base font-normal text-slate-500">dias</span></p><p class="muted mt-6">Data inicial</p><p class="mt-1 font-semibold"><?= h($schedule?->start_date?->format('d/m/Y') ?? '—') ?></p><p class="mt-6 rounded-lg bg-amber-50 p-3 text-xs leading-relaxed text-amber-900">Consulte as ocorrências pendentes e os alertas no Dashboard. A data acima é a base da programação. O CIENTE pode ser registrado no dashboard ou no histórico deste checklist.</p></aside></div>
